"""Initial migration

Revision ID: b5c64a482a62
Revises: 
Create Date: 2025-04-09 10:38:32.203708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c64a482a62'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cities_id', table_name='cities')
    op.drop_table('cities')
    op.drop_index('ix_temperature_id', table_name='temperature')
    op.drop_table('temperature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temperature',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('city_id', sa.INTEGER(), nullable=False),
    sa.Column('date_time', sa.DATETIME(), nullable=True),
    sa.Column('temperature', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temperature_id', 'temperature', ['id'], unique=False)
    op.create_table('cities',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True, unique=True),
    sa.Column('additional_info', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cities_id', 'cities', ['id'], unique=False)
    # ### end Alembic commands ###
